In [1]:
import pandas as pd
import numpy as np
import pyodbc
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [2]:
svr_name = 'KU1ICDDWV011.kunet.ae'
db_name_read = 'CACM'
db_name_write = 'CACMP'
u_name = 'cacm_user'
u_pass = 'Welcome#123'

In [3]:
eng_read = create_engine("mssql+pyodbc://"+u_name+":"+u_pass+"@"+svr_name+"/"+db_name_read+"?driver=ODBC+Driver+17+for+SQL+Server")
eng_write = create_engine("mssql+pyodbc://"+u_name+":"+u_pass+"@"+svr_name+"/"+db_name_write+"?driver=ODBC+Driver+17+for+SQL+Server")

In [32]:
!cd

C:\Users\ku1016\Desktop\CACM\Prapajhot

Extract Student Master Information

In [6]:
query_std_master = "Select * from OPENQUERY(BANNER,'select * from KU_CUSTOM.V_STUDENT_MASTER_AUDIT')"

In [7]:
df_student_master = pd.read_sql(query_std_master, eng_read)

In [25]:
df_student_master.to_excel("./data/df_student_master_P.xlsx")

Extract Student Course Schedule

In [17]:
query_crs_sced = "Select * from OPENQUERY(BANNER,'select * from KU_CUSTOM.V_STD_CRS_SCHEDULE_AUDIT')"

In [18]:
df_student_courses = pd.read_sql(query_crs_sced, eng_read)

In [26]:
df_student_courses.to_excel("./data/df_student_courses_P.xlsx")

Extract Student Attednance

In [19]:
query_std_attend = "Select * from OPENQUERY(BANNER,'select * from KU_CUSTOM.V_STUDENT_ATTENDANCE_AUDIT')"

In [20]:
df_student_attendance = pd.read_sql(query_std_attend, eng_read)

In [27]:
df_student_attendance.to_excel("./data/df_student_attendance_P.xlsx")

1. Student Master Data

In [23]:
df_student_master.head(3)

,ID,NAPO_ID,FIRST_NAME,LAST_NAME,FULL_NAME,ARABIC_NAME,ADMIT_TERM,START_DATE,GENDER,CAMPUS,...,MOBILE3,PARENT_PHONE,RESIDENCE_PHONE,POBOX,CITY,NATIONALITY,EMERGENCY_CONTACT_NAME,EMERGENCY_CONTACT_INFORMATION,ACADEMIC_STANDING,PRIMARY_ADVISOR
0,100020068,None,Mohammed,Al Khaja,Mohammed Ali Al Khaja,None,200810,2008-08-23,M,S,...,None,None,None,None,None,United Arab Emirates,None,None,None,None
1,100020083,None,Rashid,Al Murashda,Rashid Rashed Saeed Al Murashda,None,200810,2008-08-23,M,S,...,None,None,None,None,None,United Arab Emirates,None,None,None,None
2,100020008,None,Abdulla,Mohammed,Abdulla Ahmed Abdullah Mohammed,None,200810,2008-08-23,M,S,...,None,None,None,None,None,United Arab Emirates,None,None,None,None

In [24]:
df_student_master.tail(3)

,ID,NAPO_ID,FIRST_NAME,LAST_NAME,FULL_NAME,ARABIC_NAME,ADMIT_TERM,START_DATE,GENDER,CAMPUS,...,MOBILE3,PARENT_PHONE,RESIDENCE_PHONE,POBOX,CITY,NATIONALITY,EMERGENCY_CONTACT_NAME,EMERGENCY_CONTACT_INFORMATION,ACADEMIC_STANDING,PRIMARY_ADVISOR
17597,100063495,None,Omar,Galal,Omar Osama Fathi Galal,عمر أسامة فتحي جلال,202210,2022-08-29,M,A,...,None,509215223,None,Abu Dhabi,Abu Dhabi,EGYPT,None,None,None,IDIKA EKE OKORIE
17598,100063499,None,Mohamed,Karabala,Mohamed Noor Tamim Karabala,محمد نور تميم قره بلاه,202210,2022-08-29,M,A,...,None,None,None,Al Mina,Abu Dhabi,SYRIAN ARAB REPUBLIC,None,None,None,IDIKA EKE OKORIE
17599,100063505,None,Mazen,Salem,Mazen Akram Shaker Yaseen Salem,مازن اكرم شاكر يس سالم,202210,2022-08-29,M,A,...,None,554493484,None,Khaldiya,Abu Dhabi,EGYPT,None,None,None,Lourdes Vega

### 1.1 Overall Duplicates

In [33]:
df_student_master_duplicate = df_student_master[df_student_master.duplicated()]

In [34]:
df_student_master_duplicate

Empty DataFrame
Columns: [ID, NAPO_ID, FIRST_NAME, LAST_NAME, FULL_NAME, ARABIC_NAME, ADMIT_TERM, START_DATE, GENDER, CAMPUS, MAX_TERM, STUDENT_STATUS, CURRENT_TERM_ENROLLMENT_STATUS, MAX_TERM_ENROLLMENT_STATUS, MAX_TERM_ENROLLED_WITHDR_DATE, PROGRAM, COURSES, MAJOR, CONCENTRATION, MINOR, STUDENT_LEVEL, COLLEGE, CGPA, PASSPORT_ID, PASSPORT_EXP_DATE, EMIRATES_ID, BIRTH_DATE, SCHOOL_NAME, SCHOOL_SYSTEM, SCHOOL_AVG, HIGH_SCHOOL_ENGL, HIGH_SCHOOL_MATH, HIGH_SCHOOL_ARAB, HIGH_SCHOOL_PHYSICS, IELTS_OVERALL, ELTS_TEST_DATE, EMTH, EMEN, EMSAT_PHYSICS, EMSAT_ARABIC, KMT1_MATH, KMT2_MATH, KOXF_ENGLISH, TOFL_ENGLISH, KPET_PHYSICS, MOBILE1, MOBILE2, MOBILE3, PARENT_PHONE, RESIDENCE_PHONE, POBOX, CITY, NATIONALITY, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_INFORMATION, ACADEMIC_STANDING, PRIMARY_ADVISOR]
Index: []

[0 rows x 57 columns]

1.1.2 Student ID Duplicates

In [35]:
df_student_master_duplicate = df_student_master[df_student_master.duplicated(['ID'])]

In [36]:
df_student_master_duplicate

Empty DataFrame
Columns: [ID, NAPO_ID, FIRST_NAME, LAST_NAME, FULL_NAME, ARABIC_NAME, ADMIT_TERM, START_DATE, GENDER, CAMPUS, MAX_TERM, STUDENT_STATUS, CURRENT_TERM_ENROLLMENT_STATUS, MAX_TERM_ENROLLMENT_STATUS, MAX_TERM_ENROLLED_WITHDR_DATE, PROGRAM, COURSES, MAJOR, CONCENTRATION, MINOR, STUDENT_LEVEL, COLLEGE, CGPA, PASSPORT_ID, PASSPORT_EXP_DATE, EMIRATES_ID, BIRTH_DATE, SCHOOL_NAME, SCHOOL_SYSTEM, SCHOOL_AVG, HIGH_SCHOOL_ENGL, HIGH_SCHOOL_MATH, HIGH_SCHOOL_ARAB, HIGH_SCHOOL_PHYSICS, IELTS_OVERALL, ELTS_TEST_DATE, EMTH, EMEN, EMSAT_PHYSICS, EMSAT_ARABIC, KMT1_MATH, KMT2_MATH, KOXF_ENGLISH, TOFL_ENGLISH, KPET_PHYSICS, MOBILE1, MOBILE2, MOBILE3, PARENT_PHONE, RESIDENCE_PHONE, POBOX, CITY, NATIONALITY, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_INFORMATION, ACADEMIC_STANDING, PRIMARY_ADVISOR]
Index: []

[0 rows x 57 columns]

1.1.3 Student Names Duplicates - Academically dismissed & other issues

We checked each instance to verify and validate columns H, M, Q(Continued Education) ...

In [37]:
df_student_master_duplicate = df_student_master[df_student_master.duplicated(['FULL_NAME'])]

In [38]:
df_student_master_duplicate

,ID,NAPO_ID,FIRST_NAME,LAST_NAME,FULL_NAME,ARABIC_NAME,ADMIT_TERM,START_DATE,GENDER,CAMPUS,...,MOBILE3,PARENT_PHONE,RESIDENCE_PHONE,POBOX,CITY,NATIONALITY,EMERGENCY_CONTACT_NAME,EMERGENCY_CONTACT_INFORMATION,ACADEMIC_STANDING,PRIMARY_ADVISOR
2099,100058910,None,Noora,Alshehhi,Noora Mohammed Khamis Rashed Alshehhi,نوره محمد خميس راشد الشحي,202010,2020-08-23 00:00:00,F,A,...,None,None,None,None,Ras AlKaimah,United Arab Emirates,None,None,None,Vladimir Parezanovic
3940,100058270,None,Mohammad,Awadhalla,Mohammad Fadi Awadhalla,محمد فادي عوض الله,202010,2020-08-23 00:00:00,M,A,...,None,None,None,Albarsha 2 Street 29 Villa 8,Dubai,United Arab Emirates,None,None,None,None
4395,100035081,None,Alya,Alsaadi,Alya Alsaadi,None,200920,2009-11-23 00:00:00,F,S,...,None,None,None,None,Abu Dhabi,United Arab Emirates,None,None,None,None
6022,100062331,None,Ibrahim,Alraeesi,Ibrahim Khalil Ibrahim Alfaini Alraeesi,ابراهيم خليل ابراهيم الفيني الرئيسي,202210,2022-08-29 00:00:00,M,A,...,None,None,None,Muwafijah,Sharjah,United Arab Emirates,None,None,None,None
7112,100042377,None,Hend,Mohamed Ahmed Almarzooqi,Hend Ahmed Mohamed Ahmed Almarzooqi,None,201510,2015-08-23 00:00:00,F,A,...,None,None,None,AL FALAH,Abu Dhabi,United Arab Emirates,None,None,None,None
7356,100001904,None,Abdulla,Al Ali,Abdulla Rashid Al Ali,None,200710,2007-06-18 12:06:23,M,S,...,None,None,None,Abu Dhabi 77334,Abu Dhabi,United Arab Emirates,None,None,None,None
7454,100048093,None,Nouf,Alzaabi,Nouf Ebrahim Alzaabi,نوف ابراهيم سالم مسعود الزعابي,201310,2013-09-08 00:00:00,F,M,...,None,None,None,UN,UN,United Arab Emirates,None,None,None,None
8075,100046318,None,Hanan,Hamdan,Hanan Ahmad Mohammad Hamdan,حنان احمد محمد حمدان,201520,2016-01-10 00:00:00,F,P,...,None,None,None,P.O. Box 1065,Al Ain,JORDAN,None,None,00,None
8110,100052916,None,Fadi,Dawaymeh,Fadi Zeyad Dawaymeh,فادي زياد نواف دوايمه,201910,2019-08-25 00:00:00,M,A,...,None,None,None,"Abu Dhabi,behind one to one hotel, Malqatah st...",Abu Dhabi,JORDAN,--,None,None,Nahla Saeed Al Amoodi
8171,100043364,None,Fareha,Nasim,Fareha Zainab Nasim,None,201520,2016-01-10 00:00:00,F,A,...,None,None,None,Fatima Bint Mubarak Street,Abu Dhabi,PAKISTAN,None,None,None,None
8317,100061899,None,Muhammad Ahmed,Humais,Muhammad Ahmed Humais,محمد أحمد حميس,202120,2022-01-17 00:00:00,M,A,...,None,None,None,"R-1931, Block-14, Federal B Area",Karachi,PAKISTAN,None,None,None,Yahya Hasem Abdallah Zweiri
8382,100058255,None,Dima,Ali,Dima Samer Ali,ديمة سامر علي,202010,2020-08-23 00:00:00,F,A,...,None,None,None,Abu Dhabi,Abu Dhabi,JORDAN,None,None,None,None
8467,100059518,None,Muhammad,Osama,Muhammad Osama,None,202010,2020-08-23 00:00:00,M,A,...,None,None,None,Ali street house no 2 green land officer colony,Rawalpindi,PAKISTAN,None,None,None,None
9011,100035348,None,Bushra,Ehmaid,Bushra Bassam Mohamed Ehmaid,None,201010,2010-05-01 00:00:00,F,A,...,None,None,None,None,None,PALESTINE,None,None,None,None
9312,100038841,None,Shiza,Saleem,Shiza Saleem,شيزا سليم بنت محمد جافيد,201210,2012-09-02 00:00:00,F,A,...,None,None,None,HSBC Building Opposite Etisalat building Old A...,Abu Dhabi,PAKISTAN,None,None,00,None
9708,100048474,None,Mariam,Alhashmi,Mariam Abdulhameed Alsayedmohamed Alhashmi,مريم عبدالحميد السيدمحمد الهاشمي,201510,2015-08-23 00:00:00,F,Z,...,None,None,None,"P.O.Box:5852,Mohammed bin zayed city",Abu Dhabi,United Arab Emirates,FatimaElsyed Ahmed,0501955566,00,None
9787,100049147,None,Xiaoxiong,Zhang,Xiaoxiong Zhang,اكسياوكسيونج زهانج,201520,2016-01-10 00:00:00,M,P,...,None,None,None,"P.O.Box:1002249,18 Fuxue Load, Changping",Beijing,CHINA,None,None,None,None
10126,100038906,None,Mahmoud,Khalil,Mahmoud Mustafa Khalil,محمود مصطفى خليل,201210,2012-09-02 00:00:00,M,A,...,None,None,None,Airport street .. central market,Abu Dhabi,SYRIAN ARAB REPUBLIC,None,None,None,None
10230,100049400,None,Muhammad Ahmed,Humais,Muhammad Ahmed Humais,محمد أحمد محمد اجاز رشيد,201810,2018-08-28 00:00:00,M,A,...,None,None,None,P.O.Box: 38384,Abu Dhabi,PAKISTAN,--,None,00,None
10344,100045979,None,Mariam,Salmeen,Mariam Hamad Salmeen Anber Salmeen,مريم حمد سالمين عنبر سالمين,201710,2017-08-20 00:00:00,F,None,...,None,None,None,971,Baniyas East - Abu Dhabi,United Arab Emirates,None,None,00,None
10374,100050201,None,Ali,Alobaidi,Ali Khalid Ali Saleh Alobaidi,على خالد على صالح العبيدى,201610,2016-08-21 00:00:00,M,H,...,None,None,None,PO Box PO Box P.O.Box:31841,Abu Dhabi,United Arab Emirates,khaledAlobaidi,506117854,None,Faisal AlMarzooqi
10683,100042767,None,Hamad,Ali Mohammed Alhosani,Hamad Hassan Ali Mohammed Alhosani,None,201510,2015-08-23 00:00:00,M,A,...,None,None,None,AL HAMEEDYA,Al Hameedya,United Arab Emirates,None,None,None,None
11954,100049383,None,Haile,Woldesellasse,Haile Tecle Woldesellasse,هيلي تيسل ولديسلاس,201810,2018-08-28 00:00:00,M,A,...,None,None,None,"HBKU, Educational City",Doha,ERITREA,--,None,00,None
11990,100050075,None,Salama,Alheara,Salama Amer Alheara,None,201820,2019-01-13 00:00:00,F,A,...,None,None,None,"zone 34, MBZ city",Abudhabi,United Arab Emirates,None,None,None,None
13520,100041200,None,Vikas,Kumar,Vikas Kumar,ويكاس بانجات براساد كومار,201410,2014-08-24 00:00:00,M,M,...,None,None,None,"Wind Block Room No 1.08 , SAO",Abu Dhabi,INDIA,None,None,None,None
14040,100047399,None,Muhammad,Ali,Muhammad Ali,None,201110,2011-09-11 00:00:00,M,M,...,None,None,None,UN,UN,PAKISTAN,None,None,None,None
14592,100049403,None,Yohanna,Fseha,Yohanna Haile Fseha,يوحانا هيل فسيحة,201810,2018-08-28 00:00:00,F,A,...,None,None,None,19 Mike Ruta Court,Winnipeg,ERITREA,HaileElfu,971555291245,None,Banu Sizirici Yildiz
14735,100050196,None,Yusra,Alblooshi,Yusra Mohammed Moosa Ali Alblooshi,يسرا محمد موسى على البلوشي,201510,2015-08-23 00:00:00,F,Z,...,None,None,None,"P.O.Box:1032,Aldhait",Ras Al Khaimah,United Arab Emirates,MohammedAlblooshi,506479976,00,None
14924,100058223,None,Tariq,Altamimi,Tariq Saadaldin Altamimi,طارق سعدالدين التميمي,202041,2020-08-16 00:00:00,M,A,...,None,None,None,48A st. Al Barsha 2,Dubai,United Arab Emirates,None,None,None,Natalie Van Niekerk
15158,100061039,None,Mohamed,Alnufaili,Mohamed Abdulla Alnufaili,محمد عبدالله النفيلي,202110,2021-08-22 00:00:00,M,A,...,None,None,None,Al Shamkha Abu Dhabi,Abu Dhabi,United Arab Emirates,None,None,None,None
15312,100058297,None,Maitha,Alshamsi,Maitha Helal Alshamsi,ميثا هلال الشامسي,202041,2020-08-16 00:00:00,F,A,...,None,None,None,"Nahel Town, Alain, 70 St",Alain,United Arab Emirates,None,None,00,Eman Alefishat
16144,100048206,None,Sohail,Shah,Sohail Shah,None,201420,2015-01-11 00:00:00,M,M,...,None,None,None,UN,UN,INDIA,None,None,None,None
16228,100048544,None,Diana,Amin,Diana Maher Morris Amin,ديانا ماهر موريس امين,201410,2014-08-24 00:00:00,F,P,...,None,None,None,P.O. Box 25260,Abu Dhabi,EGYPT,None,None,None,None
16332,100049380,None,Karim,Moharm,Karim Ibrahim Moharm,كريم ابراهيم محمد,201810,2018-08-28 00:00:00,M,A,...,None,None,None,"383 Gamal Abdelnasser St,",Egypt,EGYPT,None,None,None,None
16333,100049382,None,Mai,Almarri,Mai Abdulsalam Almarri,مي عبدالسلام المري,201810,2018-08-28 00:00:00,F,A,...,None,None,None,"Al Zaab Area, 18 st, Villa 44",Abu Dhabi,United Arab Emirates,None,None,00,None
16819,100050135,None,Hind,Sulieman,Hind Yahya Sulieman,هند يحيى سليمان,201820,2019-01-13 00:00:00,F,A,...,None,None,None,Al Ain,Al Ain,JORDAN,--,None,None,Mohammad Eid Alsuwaidi
16821,100050151,None,Abdulaziz,Alblooshi,Abdulaziz Abbas Ahmed Yousef Alblooshi,عبدالعزيز عباس احمد يوسف البلوشى,201610,2016-08-21 00:00:00,M,H,...,None,None,None,"PO Box PO Box P.O.Box:2720,",Abu Dhabi,United Arab Emirates,AbbasAlBlooshi,506122826,None,None
16855,100057585,None,Hongtao,Zhang,Hongtao Zhang,هونجتو زانج,201920,2020-01-12 00:00:00,M,A,...,None,None,None,Masdar campus,Masdar City,CHINA,None,None,None,Isam Mustafa Janajreh
16861,100057666,None,Ahmed,Elkafrawy,Ahmed Asaad Elkafrawy,احمد اسعد الكفراوي,201920,2020-01-12 00:00:00,M,A,...,None,None,None,10 st. Abulmaati - Agouza,Giza,EGYPT,None,None,None,None
16926,100050190,None,Abdulaziz,Alsabeeha,Abdulaziz Nabeel Alsabeeha,None,201820,2019-01-13 00:00:00,M,A,...,None,None,None,"7th April St, Khuzam, Ras Al Khaimah",Abudhabi,United Arab Emirates,None,None,None,None
17004,100062240,None,Talal,AlHajeri,Talal Mohamed Salman Mohamed AlHajeri,None,201110,2011-09-11 00:00:00,M,P,...,None,None,None,P.O. Box: 6946,Abu Dhabi,United Arab Emirates,None,None,None,None
17043,100061895,None,Abeer,Awadallah,Abeer Mahmoud Awadallah,عبير محمود عوض الله,202120,2022-01-17 00:00:00,F,A,...,None,None,None,Building 32 - Apartment 4,Al Ain City,JORDAN,None,None,None,Chan Yeob Yeun
17104,100058220,None,Mahra,Aldarmaki,Mahra Khalifa Aldarmaki,مهره خليفه الدرمكي,202010,2020-08-23 00:00:00,F,A,...,None,None,None,Street 22,Khalifa City A,United Arab Emirates,None,None,None,Jamal Ahmad

In [39]:
df_comparison = pd.merge(df_student_master, df_student_master_duplicate, on='FULL_NAME', how='inner')

In [40]:
df_comparison

,ID_x,NAPO_ID_x,FIRST_NAME_x,LAST_NAME_x,FULL_NAME,ARABIC_NAME_x,ADMIT_TERM_x,START_DATE_x,GENDER_x,CAMPUS_x,...,MOBILE3_y,PARENT_PHONE_y,RESIDENCE_PHONE_y,POBOX_y,CITY_y,NATIONALITY_y,EMERGENCY_CONTACT_NAME_y,EMERGENCY_CONTACT_INFORMATION_y,ACADEMIC_STANDING_y,PRIMARY_ADVISOR_y
0,100032432,None,Alya,Alsaadi,Alya Alsaadi,None,200910,2009-08-23,F,S,...,None,None,None,None,Abu Dhabi,United Arab Emirates,None,None,None,None
1,100035081,None,Alya,Alsaadi,Alya Alsaadi,None,200920,2009-11-23,F,S,...,None,None,None,None,Abu Dhabi,United Arab Emirates,None,None,None,None
2,100045114,None,Fareha,Nasim,Fareha Zainab Nasim,فريحه زينب نسيم,201610,2016-08-21,F,A,...,None,None,None,Fatima Bint Mubarak Street,Abu Dhabi,PAKISTAN,None,None,None,None
3,100043364,None,Fareha,Nasim,Fareha Zainab Nasim,None,201520,2016-01-10,F,A,...,None,None,None,Fatima Bint Mubarak Street,Abu Dhabi,PAKISTAN,None,None,None,None
4,100049862,None,Xiaoxiong,Zhang,Xiaoxiong Zhang,اكسيو اكسيونغ زانغ,201810,2018-08-28,M,A,...,None,None,None,"P.O.Box:1002249,18 Fuxue Load, Changping",Beijing,CHINA,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,100058220,None,Mahra,Aldarmaki,Mahra Khalifa Aldarmaki,مهره خليفه الدرمكي,202010,2020-08-23,F,A,...,None,None,None,Street 22,Khalifa City A,United Arab Emirates,None,None,None,Jamal Ahmad
84,100040136,None,Mai,Almarri,Mai Abdulsalam Almarri,مي عبدالسلام المري,201310,2013-09-08,F,A,...,None,None,None,"Al Zaab Area, 18 st, Villa 44",Abu Dhabi,United Arab Emirates,None,None,00,None
85,100049382,None,Mai,Almarri,Mai Abdulsalam Almarri,مي عبدالسلام المري,201810,2018-08-28,F,A,...,None,None,None,"Al Zaab Area, 18 st, Villa 44",Abu Dhabi,United Arab Emirates,None,None,00,None
86,100048991,None,Hongtao,Zhang,Hongtao Zhang,هونجتاو زهانج,201410,2014-08-24,M,P,...,None,None,None,Masdar campus,Masdar City,CHINA,None,None,None,Isam Mustafa Janajreh
87,100057585,None,Hongtao,Zhang,Hongtao Zhang,هونجتو زانج,201920,2020-01-12,M,A,...,None,None,None,Masdar campus,Masdar City,CHINA,None,None,None,Isam Mustafa Janajreh

1.1.4 Emirates ID Duplicate