In [1]:
import pandas as pd
import numpy as np

In [39]:
sheet1 = pd.read_excel('2021-2022 POs (Contracts).xlsx',sheet_name='PO Details')

In [40]:
sheet1 = sheet1.drop_duplicates(subset='Purchase Order Number')

In [41]:
sheet21 = pd.read_excel('Sourcing (competetive vs. single)_old.xlsx',sheet_name='2021')

In [42]:
sheet21 = sheet21.drop_duplicates(subset='PO#')

In [43]:
sheet22 = pd.read_excel('Sourcing (competetive vs. single)_old.xlsx',sheet_name='2022')

In [44]:
sheet22 = sheet22.drop_duplicates(subset='PO#')

In [45]:
sheet2 = pd.concat([sheet21,sheet22]).drop_duplicates(subset='PO#')

In [49]:
sheet1

,Period Year,Po Buyer Name,Purchase Order Number,PO Status,PO Approved Date,Purchase Order Description,PO Currency,Po Amount,Vendor Name,Revision Num,Blanket PO,PR Number,PR Approval Status,PR Approval Date,RFQ Number,Tender Type,PO Type
0,2021.0,Sara Dashen Nasser Alhallaf Al Ahbabi,8.432202e+09,APPROVED,2021-01-18,NaN,AED,6138.00,LABCO L.L.C.,0.0,NaN,8432102190,APPROVED,2020-11-08,6307087-2,Limited Tender,Standard Purchase Order with AME
1,2021.0,Sara Dashen Nasser Alhallaf Al Ahbabi,8.432202e+09,APPROVED,2021-01-06,NaN,AED,2105.00,EMIRATES SCIENTIFIC & TECHNICAL SUPPLIES (LLC)...,0.0,NaN,8432102190,APPROVED,2020-11-08,6307087-2,Limited Tender,Standard Purchase Order with AME
2,2021.0,Sara Dashen Nasser Alhallaf Al Ahbabi,8.432202e+09,APPROVED,2022-04-13,Thorlabs OCT accessories,USD,901.40,"THORLABS, INC",3.0,NaN,8432102221,APPROVED,2020-12-17,NaN,Direct PO,Service Agreement with AME
3,2021.0,Sara Dashen Nasser Alhallaf Al Ahbabi,8.432202e+09,APPROVED,2021-04-22,NaN,AED,5505.00,SCHLUMBERGER MIDDLE EAST S.A,0.0,NaN,8432102223,APPROVED,2020-12-25,6328078,Limited Tender,Service Agreement with AME
4,2021.0,Sara Dashen Nasser Alhallaf Al Ahbabi,8.432202e+09,APPROVED,2021-03-16,NaN,USD,1332.00,"GELON ENERGY CO., LIMITED",0.0,NaN,8432102252,APPROVED,2021-01-28,6353100,Limited Tender,Service Agreement with AME
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688,2021.0,Sara Dashen Nasser Alhallaf Al Ahbabi,8.474200e+09,APPROVED,2021-09-14,"Extension of FM hard services contract, includ...",AED,4999520.96,GULF INDUSTRIAL SERVICES CO. (GISCO),0.0,NaN,8474100222,APPROVED,2021-07-14,6398238-2,Limited Tender,Service Agreement with AME
689,2021.0,Sara Dashen Nasser Alhallaf Al Ahbabi,8.474200e+09,APPROVED,2021-10-19,Essential Maintenance & Rectification Services...,AED,571305.18,GULF INDUSTRIAL SERVICES CO. (GISCO),0.0,NaN,8474100218,APPROVED,2021-05-09,6390474,Single Source,Service Agreement with AME
690,2021.0,Mariam Al Baloushi,8.474200e+09,APPROVED,2021-11-30,Maintenance service for Shimdzu equipment.,AED,45170.00,NAHLA MEDICAL SUPPLIES - SOLE PROPRIETORSHIP L...,0.0,NaN,8474100080,APPROVED,2021-05-09,6349115,Limited Tender,Service Agreement with AME
691,2021.0,Josilin Anthony,8.474200e+09,APPROVED,2021-12-16,RW-432209: AMC for Rheometer-MCR 302 installed...,AED,60542.77,BDH MIDDLE EAST L.L.C.,1.0,NaN,8474100226,APPROVED,2021-11-28,NaN,NaN,Service Agreement with AME
692,2022.0,Mohammad As'ad Salim Khalil,8.474200e+09,APPROVED,2022-01-20,Major service of chillers in ADRIC building.,AED,289923.00,GULF INDUSTRIAL SERVICES CO. (GISCO),0.0,NaN,8472100118,APPROVED,2020-11-08,6398226,Single Source,Service Agreement with AME

In [51]:
sheet1['Purchase Order Number'] = sheet1['Purchase Order Number'].astype('Int64').astype(str)

In [52]:
sheet1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 679 entries, 0 to 692
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Period Year                 678 non-null    float64
 1   Po Buyer Name               678 non-null    object
 2   Purchase Order Number       679 non-null    object
 3   PO Status                   678 non-null    object
 4   PO Approved Date            647 non-null    datetime64[ns]
 5   Purchase Order Description  628 non-null    object
 6   PO Currency                 678 non-null    object
 7   Po Amount                   679 non-null    float64
 8   Vendor Name                 675 non-null    object
 9   Revision Num                678 non-null    float64
 10  Blanket PO                  46 non-null     float64
 11  PR Number                   679 non-null    int64
 12  PR Approval Status          679 non-null    object
 13  PR Approval Date            675 non-null    datetime64[ns]
 14  RFQ Number                  352 non-null    object
 15  Tender Type                 636 non-null    object
 16  PO Type                     679 non-null    object
dtypes: datetime64[ns](2), float64(4), int64(1), object(10)
memory usage: 95.5+ KB

In [56]:
sheet1.merge(sheet2,left_on='Purchase Order Number',right_on='PO#',how='outer').to_excel('merge1.xlsx')

In [60]:
m = pd.read_excel('merge1.xlsx',index_col=0)

In [63]:
p = pd.read_excel('Procurement 2021-2022 POs (Variation  Type) 16 June 2022.xlsx')

In [66]:
p = p.drop_duplicates(subset='Purchase Order Number')

In [67]:
p['Purchase Order Number'] = p['Purchase Order Number'].astype('Int64').astype(str)

<ipython-input-67-db806bd65a53>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p['Purchase Order Number'] = p['Purchase Order Number'].astype('Int64').astype(str)

In [71]:
p.merge(m,left_on='Purchase Order Number',right_on='Purchase Order Number',how='outer').to_excel('final.xlsx')

In [72]:
f = pd.read_excel('final.xlsx')

In [75]:
f =f.drop_duplicates(subset='Purchase Order Number')

In [77]:
f.to_excel('final_1.xlsx')

In [79]:
p.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1523 entries, 0 to 1527
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Period Year                 1522 non-null   float64
 1   Purchase Order Number       1523 non-null   object
 2   Po Buyer Name               1522 non-null   object
 3   PO Status                   1522 non-null   object
 4   PO Approved Date            1468 non-null   datetime64[ns]
 5   Purchase Order Description  1080 non-null   object
 6   Vendor Name                 1522 non-null   object
 7   Revision Num                1522 non-null   float64
 8   Blanket PO                  15 non-null     float64
 9   PR Number                   1523 non-null   int64
 10  PR Approval Status          1523 non-null   object
 11  PR Approval Date            1479 non-null   datetime64[ns]
 12  RFQ Number                  456 non-null    object
 13  Tender Type                 1523 non-null   object
 14  PO Type                     1523 non-null   object
 15  PO Currency                 1522 non-null   object
 16  PO Value (actual Currency)  1523 non-null   float64
 17  PO Value (AED)              1523 non-null   float64
dtypes: datetime64[ns](2), float64(5), int64(1), object(10)
memory usage: 226.1+ KB

In [81]:
sheet1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 679 entries, 0 to 692
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Period Year                 678 non-null    float64
 1   Po Buyer Name               678 non-null    object
 2   Purchase Order Number       679 non-null    object
 3   PO Status                   678 non-null    object
 4   PO Approved Date            647 non-null    datetime64[ns]
 5   Purchase Order Description  628 non-null    object
 6   PO Currency                 678 non-null    object
 7   Po Amount                   679 non-null    float64
 8   Vendor Name                 675 non-null    object
 9   Revision Num                678 non-null    float64
 10  Blanket PO                  46 non-null     float64
 11  PR Number                   679 non-null    int64
 12  PR Approval Status          679 non-null    object
 13  PR Approval Date            675 non-null    datetime64[ns]
 14  RFQ Number                  352 non-null    object
 15  Tender Type                 636 non-null    object
 16  PO Type                     679 non-null    object
dtypes: datetime64[ns](2), float64(4), int64(1), object(10)
memory usage: 95.5+ KB